name: Run Update

on:
  push:
    branches:
      - dispatch

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: leethomasrh/cop-bazaar@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: leethomasrh/cop-bazaar
          event-type: my-event