#Testing-32
name: Run Update

on:
  push:
    branches:
      - use-action

jobs:
  action:
    name: Call remote action
    runs-on: ubuntu-latest
    steps:
      - uses: leethomasrh/cop-bazaar@action-yaml
        with:
          input_path: ./cop
          output_path: ./cop-output
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
