#Testing-42
name: Run Update

on:
  push:
    branches:
      - pullcode

jobs:
  steps:
    - name: Update COP output
      uses: leethomasrh/cop-bazaar@action-yaml
      with:
        input_path: ./cop
        output_path: ./cop-output
