#Testing-42
name: Run Update

on:
  push:
    branches:
      - pullcode

jobs:
  build:
    name: Run update code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout remote main branch
        uses: redhat-cop/github-actions/set-helm-version@master
        with:
          input_path: ./cop
          output_path: ./cop-output
