#Testing-42
name: Run Update

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Dispatch to `other-repo`
    runs-on: ubuntu-latest
  steps:
    - name: Emit repository_dispatch
      uses: mvasigh/dispatch-action@main
      with:
        repo: cop-bazaar
        owner: leethomasrh
        event_type: my-event
        debug: 2
