name: Run Update

on:
  push:
    branches:
      - dispatch

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: Repository dispatch
        run: |
          curl -X POST \
          -H {'Authorization' : 'token ' + secrets.GITHUB_TOKEN} \
          -u ${{ secrets.GITHUB_TOKEN }} \
          https://api.github.com/repos/leethomasrh/cop-bazaar/dispatches
#      - name: Repository Dispatch
#        uses: actions/checkout@v2
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#          repository: leethomasrh/cop-bazaar
#          types: my-event