name: Run Update

on:
  push:
    branches:
      - dispatch

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: Repository dispatch
        run: |
          curl -XPOST -H \"Accept: \
          application/vnd.github.everest-preview+json\"  \
          -H \"Content-Type: application/json\" \
          -H \"Authorization: token ${GITHUB_TOKEN}\" \
          https://api.github.com/repos/leethomasrh/cop-bazaar/dispatches \
          --data '{\"event_type\": \"my-event\"}'"
#          https://api.github.com/repos/leethomasrh/cop-bazaar/dispatches
#      - name: Repository Dispatch
#        uses: actions/checkout@v2
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#          repository: leethomasrh/cop-bazaar
#          types: my-event